import { useState } from "react";
import { Search, HelpCircle, ChevronDown, ChevronUp } from "lucide-react";

interface FAQItem {
  question: string;
  answer: string;
  category: "Products" | "Distributor" | "Payments" | "Shipping";
}

const FAQ_ITEMS: FAQItem[] = [
  {
    category: "Products",
    question: "Are Songtai Life products certified by medical authorities in Cameroon?",
    answer: "Yes. All our nutritional lines, including Cellular Vitality Pro, are fully tested and certified by the Ministry of Public Health (MINSANTE) in Cameroon. Our products comply with strict guidelines for food supplement bio-availability."
  },
  {
    category: "Products",
    question: "Can I use the Bio-Yield Max fertilizer for all categories of crops?",
    answer: "Absolutely. Bio-Yield Max liquid bio-stimulant is scientifically engineered to optimize root health, nitrogen absorption, and overall harvest weight across cacao, coffee, maize, plantains, and local organic garden vegetables."
  },
  {
    category: "Distributor",
    question: "What is the process to climb to Diamond Leader status?",
    answer: "Rank advancement is tied to two parallel parameters: your accumulated personal volume (PV) points, and the overall volume generated by your first and second-generation downline trees. Reaching Diamond unlocks 3% regional pool overrides."
  },
  {
    category: "Distributor",
    question: "Are there any annual or monthly maintenance fees to remain active?",
    answer: "No. Unlike traditional direct-selling schemes, Songtai Life does not charge recurring distributor subscription fees. Your profile remains indefinitely active as long as you make at least one product purchase every six months."
  },
  {
    category: "Payments",
    question: "How do I receive my team volume commissions in Cameroon?",
    answer: "All direct commissions and overrides are computed and settled biweekly. We utilize the secure MeSomb gateway, enabling you to transfer funds directly into your MTN Mobile Money (MoMo) or Orange Money wallet instantly."
  },
  {
    category: "Shipping",
    question: "Where can I pick up my ordered products physically?",
    answer: "We operate fully staffed regional centers in Yaoundé (Avenue Kennedy) and Douala (Akwa), open Monday to Saturday. For out-of-town distributors, we ship via trusted regional transport agencies (Finexs, Touristique, General) within 24-48 hours."
  }
];

export default function FAQ() {
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState<string>("All");
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  const categories = ["All", "Products", "Distributor", "Payments", "Shipping"];

  const filteredItems = FAQ_ITEMS.filter(item => {
    const matchesSearch = item.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          item.answer.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = activeCategory === "All" || item.category === activeCategory;
    return matchesSearch && matchesCategory;
  });

  const toggleExpand = (index: number) => {
    setExpandedIndex(expandedIndex === index ? null : index);
  };

  return (
    <div className="min-h-screen bg-stone-950 text-stone-100 py-16 font-sans text-left relative overflow-hidden">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12 relative z-10">
        
        {/* Header & Search */}
        <div className="space-y-6">
          <div className="space-y-1.5">
            <span className="text-xs uppercase tracking-widest text-[#C9A227] font-bold">Self Service</span>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">Frequently Asked Questions</h1>
            <p className="text-stone-400 text-xs">Instantly resolve questions regarding our products, rewards, or shipping nodes.</p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4">
            {/* Search Input */}
            <div className="relative flex-grow">
              <Search className="w-4 h-4 text-stone-500 absolute left-3.5 top-3.5" />
              <input
                type="text"
                placeholder="Search our knowledge base..."
                value={searchQuery}
                onChange={(e) => {
                  setSearchQuery(e.target.value);
                  setExpandedIndex(null);
                }}
                className="w-full pl-10 pr-4 py-2.5 bg-stone-900 border border-stone-850 rounded-xl text-xs text-white outline-none focus:border-[#0A7D32]"
              />
            </div>

            {/* Category selection */}
            <div className="flex flex-wrap gap-1.5 p-1 bg-stone-950 rounded-xl border border-stone-900 w-fit self-start sm:self-auto">
              {categories.map(cat => (
                <button
                  key={cat}
                  onClick={() => {
                    setActiveCategory(cat);
                    setExpandedIndex(null);
                  }}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                    activeCategory === cat ? "bg-[#0A7D32] text-white" : "text-stone-500 hover:text-stone-300"
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Accordion List */}
        {filteredItems.length === 0 ? (
          <div className="py-16 text-center text-stone-500 text-xs">
            No matching questions found in our knowledge base. Please contact our offices directly.
          </div>
        ) : (
          <div className="space-y-4">
            {filteredItems.map((item, idx) => {
              const isOpen = expandedIndex === idx;
              return (
                <div 
                  key={idx} 
                  className="bg-stone-900/25 border border-stone-850/60 rounded-2xl overflow-hidden transition-all duration-200"
                >
                  <button
                    onClick={() => toggleExpand(idx)}
                    className="w-full px-6 py-5 flex items-center justify-between text-left hover:bg-stone-900/40 cursor-pointer"
                  >
                    <div className="flex items-center gap-3.5 pr-4">
                      <HelpCircle className="w-5 h-5 text-[#C9A227] flex-shrink-0" />
                      <span className="font-extrabold text-white text-sm sm:text-base leading-snug">{item.question}</span>
                    </div>
                    {isOpen ? <ChevronUp className="w-4 h-4 text-stone-400" /> : <ChevronDown className="w-4 h-4 text-stone-400" />}
                  </button>

                  {isOpen && (
                    <div className="px-6 pb-6 pt-2 text-stone-300 text-xs sm:text-sm leading-relaxed border-t border-stone-900/60 bg-stone-950/20">
                      <p className="max-w-2xl">{item.answer}</p>
                      <span className="inline-block mt-4 text-[9px] uppercase font-bold text-stone-500 bg-stone-900 px-2 py-0.5 rounded-md">
                        {item.category}
                      </span>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}

      </div>
    </div>
  );
}
