import { SpecChapter, SchemaTable } from "../types";

export const SPEC_CHAPTERS: SpecChapter[] = [
  {
    id: "executive-summary",
    title: "1. Executive Summary",
    content: `Songtai Life is a premium direct-selling (MLM) platform designed to operate in the Cameroon market, focusing on health optimization and global prosperity.
The digital ecosystem is split into two primary services to achieve high scalability, clean decoupling, and robust performance:
- **web**: A Next.js 15 marketing storefront and distributor portal utilizing ISR (Incremental Static Regeneration) for lightning-fast speeds and fluid visual storytelling.
- **api**: A NestJS modular monolith that serves as the single source of truth for business logic, authentication, genealogy tree mutations, and payment orchestrations.

By decoupling the read-heavy content (blog, events, gallery) from transaction-critical operations (orders, wallet payouts, commissions), Songtai Life guarantees high-performance under peak distributor sign-up rushes.`,
  },
  {
    id: "system-architecture",
    title: "2. System Architecture",
    content: `The platform implements a decoupled, event-driven monolith model. 
Requests flow from the Edge CDN (Cloudflare) into either Vercel (routing Next.js marketing pages and the distributor dashboard) or Render/Fly.io (routing the core NestJS API and Payload CMS instance).
- **Session Layer**: Secure HTTP-only cookies are generated by the API and validated instantly in Next.js middleware, preventing client-side redirect loops.
- **Queueing Engine**: BullMQ backed by Redis schedules all async workloads like recalculating downline commissions, queueing email/SMS notifications, and updating the genealogy cache.
- **Storage Layer**: Media uploads bypass the main Node application and upload directly to a private Cloudflare R2 bucket with secure, signed link generation for sensitive KYC documents.`,
  },
  {
    id: "database-schema",
    title: "3. Database Schema & ERD",
    content: `PostgreSQL serves as the primary relational database, managed via Prisma. 
To ensure fast reads of complex binary or unilevel genealogy downlines, the network utilizes an adjacency-list pattern (each Distributor holds a nullable \`sponsorId\` and \`placementId\`).
Reads are heavily optimized through:
1. Redis caching of the subtree state (refreshed asynchronously via queue jobs).
2. Suffix-array calculations on the backend rather than nested recursive SQL joins on every load.

Financial variables use the \`Int\` data type representing CFA Franc (XAF) directly to bypass floating-point rounding errors (XAF does not use decimals).`,
  },
  {
    id: "api-contract",
    title: "4. API Specification & Webhooks",
    content: `All API routes return structured, standard JSON payloads. Mutating routes require strict schema validation (Zod/Class-Validator) and enforce rate-limits.
Key Payment Flow (MeSomb Integration):
1. **Initiate Payment**: Customer initiates order → API generates checkout session and returns payment intent.
2. **Mobile Money Collect**: Customer authorizes payment on MTN MoMo or Orange Money.
3. **Webhook Callback**: MeSomb sends an HTTP POST callback. The API validates the signature using HMAC-SHA256, checks for duplicate transaction IDs in the idempotency table, and marks the order as paid.
4. **Commission Dispatch**: Upon order payment, an async BullMQ job is queued to calculate and distribute downline PV points and commission balances.`,
    codeLanguage: "typescript",
    codeSnippet: `// Example MeSomb HMAC-SHA256 signature verification in NestJS
import { Injectable, CanActivate, ExecutionContext, UnauthorizedException } from '@nestjs/common';
import * as crypto from 'crypto';

@Injectable()
export class MeSombSignatureGuard implements CanActivate {
  canActivate(context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest();
    const signature = request.headers['x-mesomb-signature'];
    const secret = process.env.MESOMB_WEBHOOK_SECRET;

    if (!signature || !secret) {
      throw new UnauthorizedException('Missing signature or secret key');
    }

    const payload = JSON.stringify(request.body);
    const computedSignature = crypto
      .createHmac('sha256', secret)
      .update(payload)
      .digest('hex');

    if (computedSignature !== signature) {
      throw new UnauthorizedException('Invalid webhook signature');
    }
    return true;
  }
}`
  },
  {
    id: "distributor-genealogy",
    title: "5. Distributor & MLM Genealogy Engine",
    content: `The genealogy engine supports a high-performance network matrix. 
When a new distributor registers, they specify a public referral/sponsor code. The system uses a binary placement algorithm to append the node at the next available position or as specified by the sponsor.
- **Tree Node Generation**: Referral code format is configured as \`songtailife.cm/join?ref={distributorCode}\`.
- **Commission Calculations**:
  - **Direct Referrals**: 10% on direct sponsored member's order PV value.
  - **Unilevel Level Overrides**: Layered percentage payouts down to 5 generations (5%, 3%, 2%, 1%, 1%).
  - **Rank Achievements**: Recalculated daily via BullMQ scheduler; rank elevations (Bronze → Gold → Platinum → Diamond) trigger flat bonus distributions and unlock leadership overrides.`,
  },
  {
    id: "security-compliance",
    title: "6. Security & Compliance Hardening",
    content: `Because Songtai Life processes financial withdrawals and stores sensitive KYC data (National ID cards, passports), top-tier security measures are mandated:
- **Private Media Storage**: KYC files uploaded to Cloudflare R2 are kept strictly private; access is granted only to verified Admins via pre-signed, short-lived URLs (valid for 5 minutes).
- **Idempotency Locks**: All wallet withdrawal and payout requests generate a unique uuid client-side. The API checks the \`idempotencyKey\` against Redis before executing any payout transaction to prevent double-spend attacks.
- **Audit Logs**: Every admin action (e.g. KYC verification, rank adjustment, wallet correction) creates an immutable record tracking the Admin ID, IP address, target user, and delta state.`,
    codeLanguage: "typescript",
    codeSnippet: `// Example Audit Logging Service in NestJS
@Injectable()
export class AuditLogService {
  constructor(private readonly prisma: PrismaService) {}

  async logAction(adminId: string, action: string, targetId: string, details: any) {
    await this.prisma.auditLog.create({
      data: {
        adminId,
        action,
        targetId,
        details: JSON.stringify(details),
        timestamp: new Date(),
      }
    });
  }
}`
  }
];

export const SCHEMA_TABLES: SchemaTable[] = [
  {
    name: "USER",
    description: "Core authentication and profile table. All system roles derive from this model.",
    columns: [
      { name: "id", type: "UUID (Primary Key)", constraints: ["DEFAULT gen_random_uuid()"], description: "Unique identifier for the user account." },
      { name: "email", type: "VARCHAR(255)", constraints: ["UNIQUE", "NOT NULL"], description: "Primary email address, used for login." },
      { name: "phone", type: "VARCHAR(50)", constraints: ["UNIQUE", "NOT NULL"], description: "Mobile phone number, formatted for MeSomb payouts." },
      { name: "passwordHash", type: "VARCHAR(255)", constraints: ["NOT NULL"], description: "Securely hashed password (BCrypt/Argon2)." },
      { name: "role", type: "ENUM", constraints: ["DEFAULT 'customer'"], description: "System permissions: 'customer', 'distributor', 'admin', 'superadmin', 'content_editor'." },
      { name: "locale", type: "VARCHAR(10)", constraints: ["DEFAULT 'en'"], description: "Preferred language: 'en' or 'fr'." },
      { name: "createdAt", type: "TIMESTAMP", constraints: ["DEFAULT NOW()"], description: "Timestamp of record creation." }
    ]
  },
  {
    name: "DISTRIBUTOR",
    description: "Extends user record for MLM participation. Defines downline hierarchy.",
    columns: [
      { name: "id", type: "UUID (Primary Key)", constraints: ["DEFAULT gen_random_uuid()"], description: "Unique identifier for the distributor profile." },
      { name: "userId", type: "UUID (Foreign Key)", constraints: ["NOT NULL", "REFERENCES USER(id)"], description: "Associated user account record." },
      { name: "distributorCode", type: "VARCHAR(50)", constraints: ["UNIQUE", "NOT NULL"], description: "Public referral code used for new user signups." },
      { name: "sponsorId", type: "UUID (Foreign Key)", constraints: ["NULLABLE", "REFERENCES DISTRIBUTOR(id)"], description: "The direct sponsor who recruited this distributor." },
      { name: "placementId", type: "UUID (Foreign Key)", constraints: ["NULLABLE", "REFERENCES DISTRIBUTOR(id)"], description: "The direct parent in the binary/unilevel organizational tree structure." },
      { name: "rank", type: "ENUM", constraints: ["DEFAULT 'bronze'"], description: "Distributor rank: 'bronze', 'silver', 'gold', 'platinum', 'diamond'." },
      { name: "kycStatus", type: "ENUM", constraints: ["DEFAULT 'pending'"], description: "KYC validation state: 'pending', 'verified', 'rejected'." }
    ]
  },
  {
    name: "WALLET",
    description: "Real-time ledger of commissions and balances for Cameroon mobile money cashouts.",
    columns: [
      { name: "id", type: "UUID (Primary Key)", constraints: ["DEFAULT gen_random_uuid()"], description: "Unique identifier for the wallet." },
      { name: "distributorId", type: "UUID (Foreign Key)", constraints: ["UNIQUE", "NOT NULL", "REFERENCES DISTRIBUTOR(id)"], description: "Associated owner of the wallet." },
      { name: "balanceXaf", type: "INT", constraints: ["DEFAULT 0", "CHECK (balanceXaf >= 0)"], description: "Current wallet balance in XAF (floating point errors avoided)." },
      { name: "updatedAt", type: "TIMESTAMP", constraints: ["DEFAULT NOW()"], description: "Last transaction timestamp." }
    ]
  },
  {
    name: "COMMISSION",
    description: "Ledger recording individual commission transactions disbursed from order volumes.",
    columns: [
      { name: "id", type: "UUID (Primary Key)", constraints: ["DEFAULT gen_random_uuid()"], description: "Unique identifier for the commission." },
      { name: "distributorId", type: "UUID (Foreign Key)", constraints: ["NOT NULL", "REFERENCES DISTRIBUTOR(id)"], description: "Distributor who earned this payout." },
      { name: "orderId", type: "UUID (Foreign Key)", constraints: ["NOT NULL", "REFERENCES ORDER(id)"], description: "The customer order that triggered the volume points." },
      { name: "type", type: "ENUM", constraints: ["NOT NULL"], description: "Earning type: 'direct_referral', 'unilevel_override', 'rank_bonus'." },
      { name: "amountXaf", type: "INT", constraints: ["NOT NULL"], description: "Commission amount credited in XAF." },
      { name: "status", type: "ENUM", constraints: ["DEFAULT 'pending'"], description: "Earning status: 'pending', 'approved', 'paid'." }
    ]
  }
];
